### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by AzurIce** [AzurIce/bjtuse-wiki#4]
内容大纲：
- [ ] 一个概述页总结下 wiki 结构和使用、阅读方式
- [ ] 分几个部分（按照 mkdocs 的 nav 和 section）
    - [ ] ...
- [ ] ...

大致思路：
from @YXHXianYu
- [ ] 未来去向
比如：就业、保研、考研、出国等。
然后主要写：介绍 + 应该怎么做。
然后主要多写一些例子，给大家一些参考。

- [ ] 计算机相关方向简介（学术界、工业界）

- [ ] 软件学院课程相关

from @AzurIce 
- [ ] 一些资源整理
- [ ] 一些常识（这块可能很杂，文件扩展名、路径、字符编码什么的）
- [ ] 一些基础技能（markdown、git）
- [ ] GitHub 协作

**Comment by AzurIce** [comment]
贡献方式先参考：[如何参与 - OI Wiki](https://oi-wiki.org/intro/htc/#pull-request-%E4%BF%A1%E6%81%AF%E6%A0%BC%E5%BC%8F%E8%A7%84%E8%8C%83)

**Comment by AzurIce** [comment]
感觉框子搭起来之前，PR 可以稍微随意一些，不然反而效率会低很多。

Commit、目录结构、文件名什么的符合规范就好：
- 文件名用英文，使用 `-` 隔开
- 图片等内容放在相对于页面的 `./_assets/<page_name>-<number>.png` 目录下（格式随意，保证大小合适、清晰）
  如果需要限定特定主题（light 或 dark），则在名称结尾添加 `-light` 或 `-dark`。使用时见：https://squidfunk.github.io/mkdocs-material/reference/images/#light-and-dark-mode
  

关键是先写，有了内容之后格式结构什么的都好调整。
